MeetingMinutes/Models/MeetingItem.cs
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;

namespace MeetingMinutes.Models
{
    public class MeetingItem
    {
        [Key]
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MeetingItemID { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        [DataType(DataType.DateTime), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime Deadline { get; set; } =  DateTime.Now;
        [Display(Name ="Assigned To")]
        public string AssignedTo { get; set; }
        [Display(Name ="Requested By")]
        public string RequestedBy { get; set; }
        [Display(Name = "Change Requested")]
        public bool ChangeRequested { get; set; }

        [Required]
        [Display(Name = "Visible in minutes")]
        public bool VisibleInMinutes { get; set; } = true;

        [NotMapped]
        public List<IFormFile>? Files { get; set; }

        public string? FileAttachment { get; set; }

        public string?  FileName { get; set; }

        public string? FileType { get; set; }


        //Navigation Properties
        public int Meetingid { get; set; }
        public Meeting Meeting { get; set; }

        public int RiskLevelid { get; set; }
        public RiskLevel RiskLevel { get; set; }

    }
}

MeetingMinutes/Controllers/MeetingItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MeetingMinutes.Data;
using MeetingMinutes.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace MeetingMinutes.Controllers
{
    public class MeetingItemsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IWebHostEnvironment _environment;

        public MeetingItemsController(ApplicationDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: MeetingItems
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.MeetingItems.Include(m => m.Meeting).Include(m => m.RiskLevel);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: MeetingItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meetingItem = await _context.MeetingItems
                .Include(m => m.Meeting)
                .Include(m => m.RiskLevel)
                .FirstOrDefaultAsync(m => m.Meetingid== id);
            if (meetingItem == null)
            {
                return NotFound();
            }

            return View(meetingItem);
        }

        // GET: MeetingItems/Create
        public IActionResult Create(int meetingid)
        {
            ViewData["Meetingid"] = new SelectList(_context.Meetings, "MeetingID", "CreatedBy", meetingid);
            ViewData["RiskLevelid"] = new SelectList(_context.RiskLevels, "RiskLevelID", "RiskLevelID");
            return View();
        }

        // POST: MeetingItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MeetingItemID,Description,Deadline,AssignedTo,RequestedBy,ChangeRequested,VisibleInMinutes,Meetingid,RiskLevelid")] MeetingItem meetingItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(meetingItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Meetingid"] = new SelectList(_context.Meetings, "MeetingID", "CreatedBy", meetingItem.Meetingid);
            ViewData["RiskLevelid"] = new SelectList(_context.RiskLevels, "RiskLevelID", "RiskLevelID", meetingItem.RiskLevelid);
            return View(meetingItem);
        }

        // GET: MeetingItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meetingItem = await _context.MeetingItems.FindAsync(id);
            if (meetingItem == null)
            {
                return NotFound();
            }
            ViewData["Meetingid"] = new SelectList(_context.Meetings, "MeetingID", "CreatedBy", meetingItem.Meetingid);
            ViewData["RiskLevelid"] = new SelectList(_context.RiskLevels, "RiskLevelID", "RiskLevelID", meetingItem.RiskLevelid);
            return View(meetingItem);
        }

        // POST: MeetingItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MeetingItemID,Description,Deadline,AssignedTo,RequestedBy,ChangeRequested,VisibleInMinutes,Meetingid,RiskLevelid")] MeetingItem meetingItem)
        {
            if (id != meetingItem.MeetingItemID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(meetingItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeetingItemExists(meetingItem.MeetingItemID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Meetingid"] = new SelectList(_context.Meetings, "MeetingID", "CreatedBy", meetingItem.Meetingid);
            ViewData["RiskLevelid"] = new SelectList(_context.RiskLevels, "RiskLevelID", "RiskLevelID", meetingItem.RiskLevelid);
            return View(meetingItem);
        }

        public IActionResult ListItems(int meetingId)
        {
            MasterDetailViewModel model = new MasterDetailViewModel
            {
                Meetings = _context.Meetings.ToList(),
                SelectedMeeting = _context.Meetings.Find(meetingId),
                DataEntryTarget = DataEntryTargets.MeetingItems,
                DataDisplayMode = DataDisplayModes.Read

            };
            _context.Entry(model.SelectedMeeting).Collection(meeting => meeting.MeetingItems).Load();
            return View("Main", model);
        }

        [HttpPost]
        public IActionResult List(int meetingId)
        {
            MasterDetailViewModel model = new MasterDetailViewModel
            {
                Meetings = _context.Meetings.ToList(),
                SelectedMeeting = _context.Meetings.Find(meetingId),
                DataEntryTarget = DataEntryTargets.MeetingItems,
                DataDisplayMode = DataDisplayModes.Read

            };

            _context.Entry(model.SelectedMeeting).Collection(meeting => meeting.MeetingItems).Load();
            return View("Main", model);
        }

        [HttpPost]
        public IActionResult Select(int meetingId, int meetingItemId)
        {
            MasterDetailViewModel model = new MasterDetailViewModel
        {
            Meetings = _context.Meetings.ToList(),
            SelectedMeeting = _context.Meetings.Find(meetingId),
            SelectedMeetingItem = _context.MeetingItems.Find(meetingItemId),
            DataEntryTarget = DataEntryTargets.MeetingItems,
            DataDisplayMode = DataDisplayModes.Read


        };

            _context.Entry(model.SelectedMeeting).Collection(meeting => meeting.MeetingItems).Load();
            ViewBag.RiskLevel = _context.RiskLevels.Where(l =>
                l.RiskLevelID == model.SelectedMeetingItem.RiskLevelid).First().Name;
            return View("Main", model);
        }

        [HttpPost]
        public IActionResult InsertEntry(int meetingId)
        {
            MasterDetailViewModel model = new MasterDetailViewModel
            {
                Meetings = _context.Meetings.ToList(),
                SelectedMeeting = _context.Meetings.Find(meetingId),
                SelectedMeetingItem = null,
                DataEntryTarget = DataEntryTargets.MeetingItems,
                DataDisplayMode = DataDisplayModes.Insert

                
            };
            List<ApplicationUser> newparticipantlist = new List<ApplicationUser>();

            // getting data from database using ef core //
            newparticipantlist = (from user in _context.MeetingParticipants.Where(m => m.MeetingId == meetingId)
                                  select user.User).ToList();


            // inserting selected item in list //
            newparticipantlist.Insert(0, new ApplicationUser { Id = "", UserName = "select" });

            // assigning applicationuserslist to viewbag.listofapplicationusers  //
            ViewBag.listofparticipants = newparticipantlist;
            _context.Entry(model.SelectedMeeting).Collection(meeting => meeting.MeetingItems).Load();

            return View("Main", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult InsertSave( MeetingItem item)
        //public async Task<IActionResult> InsertSave([Bind("MeetingItemID,Description,Deadline,AssignedTo,RequestedBy,ChangeRequested,VisibleInMinutes,Meetingid,RiskLevelid")] MeetingItem item)
        {

            /*  var MyMeetingItem = new MeetingItem
              {
                  Description = item.Description,
                  RequestedBy = item.RequestedBy,
                  Meetingid = item.Meetingid,
                  VisibleInMinutes = true,
                  Deadline = DateTime.Now


              }; */

            try
            {
                //Add Guid
                var addGuid = Convert.ToString(Guid.NewGuid());

                if (item.Files != null)
                {
                    foreach (var formfile in item.Files)
                    {
                        string path = @$"{_environment.WebRootPath}\files\ {string.Concat(addGuid, formfile.FileName)}";

                        using var fileStream = new FileStream(path, FileMode.Create);
                        formfile.CopyTo(fileStream);
                        item.FileName = formfile.FileName;
                        item.FileAttachment = path;
                        break;
                    }

                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw;
            }
            _context.MeetingItems.Add(item);
          _context.SaveChanges();

            MasterDetailViewModel model = new MasterDetailViewModel
            {
                

                Meetings = _context.Meetings.ToList(),

MeetingMinutes/Views/MeetingItems/Create.cshtml
@model MeetingMinutes.Models.MeetingItem

@{
    ViewData["Title"] = "Create New Note";
}

<h1>Create</h1>

<h4>MeetingItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignedTo" class="control-label"></label>
                <input asp-for="AssignedTo" class="form-control" />
                <span asp-validation-for="AssignedTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestedBy" class="control-label"></label>
                <input asp-for="RequestedBy" class="form-control" />
                <span asp-validation-for="RequestedBy" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ChangeRequested" /> @Html.DisplayNameFor(model => model.ChangeRequested)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="VisibleInMinutes" /> @Html.DisplayNameFor(model => model.VisibleInMinutes)
                </label>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="Meetingid" class ="form-control" asp-items="ViewBag.Meetingid" value="ViewBag.Meetingid">
            </div>
            <div class="form-group">
                <label asp-for="RiskLevelid" class="control-label"></label>
                <select asp-for="RiskLevelid" class ="form-control" asp-items="ViewBag.RiskLevelid"></select>
            </div>
            <div class="form-group">
                <partial name="_upload" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MeetingMinutes/Views/MeetingItems/Delete.cshtml
@model MeetingMinutes.Models.MeetingItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MeetingItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssignedTo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssignedTo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequestedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequestedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChangeRequested)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChangeRequested)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VisibleInMinutes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VisibleInMinutes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RiskLevel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RiskLevel.RiskLevelID)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MeetingItemID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MeetingMinutes/Views/MeetingItems/Details.cshtml
@model MeetingMinutes.Models.MeetingItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MeetingItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssignedTo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssignedTo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequestedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequestedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChangeRequested)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChangeRequested)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VisibleInMinutes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VisibleInMinutes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RiskLevel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RiskLevel.RiskLevelID)
        </dd>
    </dl>
</div>
<div class="linkHover">
    <a class="anchorTags" asp-action="Edit" asp-route-id="@Model.MeetingItemID">Edit</a> |
    <a class="anchorTags" asp-action="Index">Back to List</a>
</div>

MeetingMinutes/Views/MeetingItems/Edit.cshtml
@model MeetingMinutes.Models.MeetingItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MeetingItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MeetingItemID" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignedTo" class="control-label"></label>
                <input asp-for="AssignedTo" class="form-control" />
                <span asp-validation-for="AssignedTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestedBy" class="control-label"></label>
                <input asp-for="RequestedBy" class="form-control" />
                <span asp-validation-for="RequestedBy" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ChangeRequested" /> @Html.DisplayNameFor(model => model.ChangeRequested)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="VisibleInMinutes" /> @Html.DisplayNameFor(model => model.VisibleInMinutes)
                </label>
            </div>
             <div class="form-group">
                <input type="hidden" asp-for="Meetingid" class ="form-control" asp-items="ViewBag.Meetingid" value="ViewBag.Meetingid">
            </div>
            <div class="form-group">
                <label asp-for="RiskLevelid" class="control-label"></label>
                <select asp-for="RiskLevelid" class="form-control" asp-items="ViewBag.RiskLevelid"></select>
                <span asp-validation-for="RiskLevelid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MeetingMinutes/Views/MeetingItems/Index.cshtml
@model IEnumerable<MeetingMinutes.Models.MeetingItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deadline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssignedTo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequestedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChangeRequested)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VisibleInMinutes)
            </th>
            <th>
            <th>
                @Html.DisplayNameFor(model => model.RiskLevel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deadline)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssignedTo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RequestedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChangeRequested)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VisibleInMinutes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RiskLevel.RiskLevelID)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MeetingItemID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MeetingItemID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MeetingItemID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MeetingMinutes/Views/MeetingItems/_InsertMeetingItem.cshtml
@model MeetingItem

<!--<head>
<style>
table {
   width: 100%;
 }

</style>
</head> -->

<br>
<h2><b>Insert new Meeting Note</b></h2>

<form method="post">

    <input type="hidden" asp-for="Meetingid" />

    
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="4" cols="50"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignedTo" class="control-label"></label>
                <input asp-for="AssignedTo" class="form-control" />
                <span asp-validation-for="AssignedTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestedBy" class="control-label"></label>
                <input asp-for="RequestedBy" class="form-control" />
                <span asp-validation-for="RequestedBy" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ChangeRequested" /> @Html.DisplayNameFor(model => model.ChangeRequested)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="VisibleInMinutes" /> @Html.DisplayNameFor(model => model.VisibleInMinutes)
                </label>
            </div>
            
            <div class="form-group">
                <label asp-for="RiskLevel" class="control-label"></label>
                <input type="text" asp-for="RiskLevelid" value="1"/>
              <!--  <select asp-for="RiskLevelid" class ="form-control" asp-items="ViewBag.RiskLevelid"></select> -->
            </div>
            <div class="form-group">
            <input type="submit"
                       value="Save"
                       class="btn customBtnPurple"
                       asp-controller="MeetingItems"
                       asp-action="InsertSave"
                       asp-route-meetingid="@Model.Meetingid" />
            </div>

            <div class="form-group">
            <input type="submit"
                       value="Cancel"
                       class="btn customBtnPurple"
                       asp-controller="MeetingItems"
                       asp-action="CancelEntry"
                       asp-route-meetingid="@Model.Meetingid" />
            </div>
            

    
    
</form>

MeetingMinutes/Views/MeetingItems/_ShowMeetingItem.cshtml
@model MeetingItem


<h2>Edit Meeting Item : @Model.Description</h2>

<form method="post">
    <table border="1" cellpadding="10">
        <tr>
            <td>Description :</td>
            <td>@Model.Description</td>
        </tr>
        <tr>
            <td>Requested By :</td>
            <td>@Model.RequestedBy</td>
        </tr>
        <tr>
            <td>Deadline</td>
            <td>@Model.Deadline</td>
        </tr>
        <tr>
            <td>Change Requested</td>
            <td>@Model.ChangeRequested</td>
        </tr>
        <tr>
            <td>Assigned To</td>
            <td>@Model.AssignedTo</td>
        </tr>
        <tr>
            <td>Visible in minutes</td>
            <td>@Model.VisibleInMinutes</td>
        </tr>
        <tr>
            <td>Risk Level</td>
            <td>@Model.RiskLevelid</td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit"
                       class="btn customBtnPurple"
                       value="Edit"
                       asp-controller="MeetingItems"
                       asp-action="UpdateEntry"
                       asp-route-meetingid="@Model.Meetingid"
                       asp-route-meetingitemid="@Model.MeetingItemID"/>

                <input type="submit"
                       class="btn customBtnPurple"
                       value="Delete"
                       asp-controller="MeetingItems"
                       asp-action="Delete"
                       asp-route-meetingid="@Model.Meetingid" 
                       asp-route-meetingitemid="@Model.MeetingItemID"/>

                <input type="submit"
                       class="btn customBtnPurple"
                       value="Cancel"
                       asp-controller="MeetingItems"
                       asp-action="CancelSelection"
                       asp-route-meetingid="@Model.Meetingid" />
                
            </td>
        </tr>
    </table>
</form>

MeetingMinutes/Views/MeetingItems/_UpdateMeetingItem.cshtml
@model MeetingItem

<h2>Edit Meeting Item : @Model.Description</h2>

<form method="post">
     <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="4" cols="50"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignedTo" class="control-label"></label>
                <input asp-for="AssignedTo" class="form-control" />
                <span asp-validation-for="AssignedTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestedBy" class="control-label"></label>
                <input asp-for="RequestedBy" class="form-control" />
                <span asp-validation-for="RequestedBy" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ChangeRequested" /> @Html.DisplayNameFor(model => model.ChangeRequested)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="VisibleInMinutes" /> @Html.DisplayNameFor(model => model.VisibleInMinutes)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="RiskLevel" class="control-label"></label>
                <input type="text" asp-for="RiskLevelid" value="1"/>
              <!--  <select asp-for="RiskLevelid" class ="form-control" asp-items="ViewBag.RiskLevelid"></select> -->
            </div>
        
           <div class="form-group">
                <input type="submit"
                       class="btn customBtnPurple"
                       value="Save"
                       asp-controller="MeetingItems"
                       asp-action="UpdateSave"
                       asp-route-meetingid="@Model.Meetingid"
                       asp-route-meetingitemid="@Model.MeetingItemID"/>

                <input type="submit"
                       class="btn customBtnPurple"
                       value="Cancel"
                       asp-controller="MeetingItems"
                       asp-action="CancelEntry"
                       asp-route-meetingid="@Model.Meetingid"
                       asp-route-meetingitemid="@Model.MeetingItemID"/>
            </div>
</form>