MeetingMinutes/Models/Meeting.cs
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;

namespace MeetingMinutes.Models
{
    public enum Status
     { 
            New,
            Started,
            Finished
    }
    public class Meeting
    {
        [Key]
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MeetingID { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        public DateTime DateCreated { get; set; } = DateTime.Now; //The date when the record was created

        [Required]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }
        //[ForeignKey("CreatedBy")]

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Date Updated")]
        public DateTime DateUpdated { get; set; } = DateTime.Now;

        [Required]
        [Display(Name = "Meeting Date")]
        [DataType(DataType.DateTime)]
        public DateTime MeetingDate { get; set; } = DateTime.Now;

        public Status Status { get; set; }

        [Required]
        public string Title { get; set; } //The title of the meeting  

        [Required]
        [Display(Name = "External Participants")]
        public string ExternalParticipants { get; set; } // A comma-separated string, keeping the mails of external(not registered in the system) participants.

        //Navigation Properties
        public List<MeetingItem> MeetingItems { get; set; }
        [Display(Name = "Meeting Participants")]
        public virtual ICollection<MeetingParticipant> MeetingParticipants { get; set; }

    }
}

MeetingMinutes/Models/MeetingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MeetingMinutes.Models
{
    public class MeetingViewModel
    {
        public int MeetingID { get; set; }
        
        [DataType(DataType.DateTime)]
        public DateTime DateCreated { get; set; } //The date when the record was created

        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Date Updated")]
        public DateTime DateUpdated { get; set; }

        [Display(Name = "Meeting Date"), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        [DataType(DataType.DateTime)]
        [Required]
        public DateTime MeetingDate { get; set; } = DateTime.Now;

        public Status Status { get; set; }
        [Required]
        public string Title { get; set; } //The title of the meeting  

        [Display(Name = "External Participants")]
        [Required]
        public string ExternalParticipants { get; set; } // A comma-separated string, keeping the mails of external(not registered in the system) participants.

        [Display(Name = "Internal Participants")]
        public List<CheckBoxViewModel> MeetingParticipants { get; set; }
    }
}

MeetingMinutes/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MeetingMinutes.Data;
using MeetingMinutes.Models;
using Microsoft.AspNetCore.Authorization;

namespace MeetingMinutes.Controllers
{
    [Authorize]
    public class MeetingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MeetingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Meetings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Meetings.ToListAsync());
        }

        // GET: Upcoming
        public async Task<IActionResult> Upcoming()
        {
            var meetings = await _context.Meetings.Where(j => (j.MeetingDate > DateTime.Now)&&(j.Status!=Status.Finished)).ToListAsync();
            var meetingsviewmodels = new List<MeetingViewModel>();
            foreach (var meeting in meetings)
            {
                if (meeting == null)
                {
                    return NotFound();
                }
                var Results = from user in _context.Users
                              select new
                              {

                                  Id = user.Id,
                                  FullName = user.FullName,
                                  Checked = ((from ab in _context.MeetingParticipants
                                              where (ab.MeetingId == meeting.MeetingID) & (ab.UserId == user.Id)
                                              select ab).Count() > 0),
                              };
                var MyViewModel = new MeetingViewModel();
                MyViewModel.MeetingID = meeting.MeetingID;
                MyViewModel.DateUpdated = meeting.DateUpdated;
                MyViewModel.CreatedBy = meeting.CreatedBy;
                MyViewModel.MeetingDate = meeting.MeetingDate;
                MyViewModel.ExternalParticipants = meeting.ExternalParticipants;
                MyViewModel.DateCreated = meeting.DateCreated;
                MyViewModel.Title = meeting.Title;
                MyViewModel.Status = meeting.Status;

                var MyCheckBoxList = new List<CheckBoxViewModel>();
                foreach (var item in Results)
                {
                    MyCheckBoxList.Add(new CheckBoxViewModel
                    {
                        Id = item.Id,
                        FullName = item.FullName,
                        IsChecked = item.Checked
                    });
                }
                MyViewModel.MeetingParticipants = MyCheckBoxList;
                meetingsviewmodels.Add(MyViewModel);
            }
            return View("UpcomingList", meetingsviewmodels);
        }
        // GET: History
        public async Task<IActionResult> History()
        {
            var meetings = await _context.Meetings.Where(j => (j.MeetingDate < DateTime.Now) || (j.Status==Status.Finished)).ToListAsync();
            var meetingsviewmodels = new List<MeetingViewModel>();
            foreach (var meeting in meetings)
            {
                if (meeting == null)
                {
                    return NotFound();
                }
                var Results = from user in _context.Users
                              select new
                              {

                                  Id = user.Id,
                                  FullName = user.FullName,
                                  Checked = ((from ab in _context.MeetingParticipants
                                              where (ab.MeetingId == meeting.MeetingID) & (ab.UserId == user.Id)
                                              select ab).Count() > 0),
                              };
                var MyViewModel = new MeetingViewModel();
                MyViewModel.MeetingID = meeting.MeetingID;
                MyViewModel.DateUpdated = meeting.DateUpdated;
                MyViewModel.CreatedBy = meeting.CreatedBy;
                MyViewModel.MeetingDate = meeting.MeetingDate;
                MyViewModel.ExternalParticipants = meeting.ExternalParticipants;
                MyViewModel.DateCreated = meeting.DateCreated;
                MyViewModel.Title = meeting.Title;
                MyViewModel.Status = meeting.Status;

                var MyCheckBoxList = new List<CheckBoxViewModel>();
                foreach (var item in Results)
                {
                    MyCheckBoxList.Add(new CheckBoxViewModel
                    {
                        Id = item.Id,
                        FullName = item.FullName,
                        IsChecked = item.Checked
                    });
                }
                MyViewModel.MeetingParticipants = MyCheckBoxList;
                meetingsviewmodels.Add(MyViewModel);
            }
            return View("HistoryList", meetingsviewmodels);
        }

        // GET: Meetings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings
                .FirstOrDefaultAsync(m => m.MeetingID == id);
            if (meeting == null)
            {
                return NotFound();
            }

            var Results = from user in _context.Users
                          select new
                          {

                              Id = user.Id,
                              FullName = user.FullName,
                              Checked = ((from ab in _context.MeetingParticipants
                                          where (ab.MeetingId == id) & (ab.UserId == user.Id)
                                          select ab).Count() > 0),
                          };
            var MyViewModel = new MeetingViewModel();
            MyViewModel.MeetingID = id.Value;
            MyViewModel.DateUpdated = meeting.DateUpdated;
            MyViewModel.CreatedBy = meeting.CreatedBy;
            MyViewModel.MeetingDate = meeting.MeetingDate;
            MyViewModel.ExternalParticipants = meeting.ExternalParticipants;
            MyViewModel.DateCreated = meeting.DateCreated;
            MyViewModel.Title = meeting.Title;
            MyViewModel.Status = meeting.Status;

            var MyCheckBoxList = new List<CheckBoxViewModel>();
            foreach (var item in Results)
            {
                MyCheckBoxList.Add(new CheckBoxViewModel
                {
                    Id = item.Id,
                    FullName = item.FullName,
                    IsChecked = item.Checked
                });
            }
            MyViewModel.MeetingParticipants = MyCheckBoxList;
            return View(MyViewModel);
        }


        // GET: Meetings/Create
        public IActionResult Create()
        {
            /*
           // για εμφανιση λιστασ με users //
           List<ApplicationUser> newparticipantlist = new List<ApplicationUser>();

           // getting data from database using ef core //
           newparticipantlist = (from user in _context.Users
                                 select user).ToList();


           // inserting selected item in list //
           newparticipantlist.Insert(0, new ApplicationUser { Id = "", UserName = "select" });

           // assigning applicationuserslist to viewbag.listofapplicationusers  //
           ViewBag.listofparticipants = newparticipantlist;
            */
            var Results = from user in _context.Users
                          select new
                          {

                              Id = user.Id,
                              FullName = user.FullName,
                              Checked = false,
                          };

            var newMeeting = new Meeting();
            var MyViewModel = new MeetingViewModel {
                MeetingID = newMeeting.MeetingID,
                DateUpdated = newMeeting.DateUpdated,
                DateCreated = newMeeting.DateCreated,
                CreatedBy = newMeeting.CreatedBy,
                MeetingDate = newMeeting.MeetingDate,
                ExternalParticipants = newMeeting.ExternalParticipants,
                Status = newMeeting.Status,
                Title = newMeeting.Title,
            };
            var MyCheckBoxList = new List<CheckBoxViewModel>();
            foreach (var item in Results)
            {
                MyCheckBoxList.Add(new CheckBoxViewModel
                {
                    Id = item.Id,
                    FullName = item.FullName,
                    IsChecked = item.Checked
                });
            }
            MyViewModel.MeetingParticipants = MyCheckBoxList;

            return View(MyViewModel);

        }

        // POST: Meetings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MeetingViewModel meeting)
        {
            if (ModelState.IsValid)
            {

                var MyMeeting = new Meeting {
                    CreatedBy = User.Identity.Name,
                    MeetingDate = meeting.MeetingDate,
                    ExternalParticipants = meeting.ExternalParticipants,
                    Title = meeting.Title
                };
                _context.Add(MyMeeting);
                await _context.SaveChangesAsync();
                foreach (var participant in meeting.MeetingParticipants)
                {
                    if (participant.IsChecked)
                    {
                        _context.MeetingParticipants.Add(
                            new MeetingParticipant()

MeetingMinutes/Views/Meetings/Create.cshtml
@model MeetingMinutes.Models.MeetingViewModel


@{
    ViewData["Title"] = "Create";
}

<h2><b>Schedule a new Meeting</b></h2>
<hr class="pb-3"/>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MeetingDate" class="control-label"></label>
                <input asp-for="MeetingDate" type="datetime-local" class="form-control" />
                <span asp-validation-for="MeetingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeetingParticipants" class="control-label"></label>
                @for (int i=0; i<Model.MeetingParticipants.Count(); i++)
                {
                    <br />
                    @Html.EditorFor(m => Model.MeetingParticipants[i].IsChecked)
                    @Html.DisplayFor(m => Model.MeetingParticipants[i].FullName)
                    @Html.HiddenFor(m => Model.MeetingParticipants[i].FullName)
                    @Html.HiddenFor(m => Model.MeetingParticipants[i].Id)
                }
                <span asp-validation-for="ExternalParticipants" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExternalParticipants" class="control-label"></label>
                <input asp-for="ExternalParticipants" class="form-control" />
                <span asp-validation-for="ExternalParticipants" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn customBtnPurple" />
            </div>
        </form>
    </div>
</div>






<div class="linkHover" > 
    <a class="anchorTags" asp-action="Upcoming">Back to Upcoming List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MeetingMinutes/Views/Meetings/Delete.cshtml
@model MeetingMinutes.Models.MeetingViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="row">

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateUpdated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateUpdated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeetingDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingParticipants)
        </dt>
        <dd class = "col-sm-10">
            @foreach(var participant in Model.MeetingParticipants)
            {
                if (participant.IsChecked)
                {
                    <div>@participant.FullName</div>
                }
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExternalParticipants)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExternalParticipants)
        </dd>
    </dl>
    
    <form class="d-flex" asp-action="Delete">
        <input type="hidden" asp-for="MeetingID" />
        <input type="submit" value="Delete" class="btn customBtnPurple" />
        <div class="linkHover pt-1"> <span class="pl-2"> | </span> <a class="anchorTags" href='javascript:history.go(-1)'>Back to List</a></div>
    </form>
</div>

MeetingMinutes/Views/Meetings/Details.cshtml
@model MeetingMinutes.Models.MeetingViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateUpdated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateUpdated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeetingDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingParticipants)
        </dt>
        <dd class = "col-sm-10">
            @foreach(var participant in Model.MeetingParticipants)
            {
                if (participant.IsChecked)
                {
                    <div>@participant.FullName</div>
                }
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExternalParticipants)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExternalParticipants)
        </dd>
    </dl>
</div>
<div class="linkHoverGrey">
     <a class="anchorTagsPurple" asp-controller="MeetingItems" asp-action="ListItems" asp-route-meetingId="@Model.MeetingID">Meeting Notes Details</a>
    <span class="pl-2"> | </span>
     <!-- COMMENT OUT -->
    <!--<a asp-action="Edit" asp-route-id="@Model.MeetingID">Edit</a> | -->
    <a class="anchorTagsPurple" href='javascript:history.go(-1)'>Back to List</a>
</div>

MeetingMinutes/Views/Meetings/Edit.cshtml
@model MeetingMinutes.Models.MeetingViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Meeting</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MeetingID" />
            <div class="form-group">
                <label asp-for="MeetingDate" class="control-label"></label>
                <input asp-for="MeetingDate" class="form-control" />
                <span asp-validation-for="MeetingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="Html.GetEnumSelectList(typeof (Status))"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExternalParticipants" class="control-label"></label>
                <input asp-for="ExternalParticipants" class="form-control" />
                <span asp-validation-for="ExternalParticipants" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeetingParticipants" class="control-label"></label>
                @for (int i=0; i<Model.MeetingParticipants.Count(); i++)
                {
                    <br />
                    @Html.EditorFor(m => Model.MeetingParticipants[i].IsChecked)
                    @Html.DisplayFor(m => Model.MeetingParticipants[i].FullName)
                    @Html.HiddenFor(m => Model.MeetingParticipants[i].FullName)
                    @Html.HiddenFor(m => Model.MeetingParticipants[i].Id)
                }
                <span asp-validation-for="ExternalParticipants" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn customBtnPurple" />
            </div>
        </form>
    </div>
</div>

<div class="linkHover">
    <a class="anchorTags" href='javascript:history.go(-1)'>Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MeetingMinutes/Views/Meetings/HistoryList.cshtml
@model IEnumerable<MeetingMinutes.Models.MeetingViewModel>

@{
    ViewData["Title"] = "HistoryList";
}

<h2><b>Past Meetings</b></h2>
<hr class="pb-3"/>

@if (!Model.Any()){
     <tr><td colspan="4">There are no Past Meetings. 

    </td></tr>
}
else{
    <table border="1" cellpadding="10">
        <thead>
            <tr bgcolor="#845460" style="color:#EAD3CB;">
                <th>
                    @Html.DisplayNameFor(model => model.CreatedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateUpdated)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MeetingDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MeetingParticipants)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ExternalParticipants)
                </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateUpdated)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MeetingDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                @foreach(var participant in item.MeetingParticipants)
                {
                    if (participant.IsChecked)
                    {
                        <div>@participant.FullName</div>
                    }
                }</td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExternalParticipants)
                </td>
                <td class="linkHoverGrey">                
                    <a class="anchorTagsPurple" asp-action="Details" asp-route-id="@item.MeetingID">Details</a>                 
                </td>
            </tr>
    }
        </tbody>
    </table>
}

MeetingMinutes/Views/Meetings/Index.cshtml
@model IEnumerable<MeetingMinutes.Models.Meeting>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<!--
<p> 
    <a asp-action="Create">Create New</a>
</p> -->

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateUpdated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MeetingDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExternalParticipants)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateUpdated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeetingDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExternalParticipants)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MeetingID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MeetingID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MeetingID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MeetingMinutes/Views/Meetings/UpcomingList.cshtml
@model IEnumerable<MeetingMinutes.Models.MeetingViewModel>

@{
    ViewData["Title"] = "UpcomingList";
}

<h2><b>Upcoming Meetings</b></h2>
<hr class="pb-3"/>

@if (!Model.Any()){
    <tr>
        
        <td colspan="4">There are no Upcoming Meetings. 
             <br/>
             <div class="linkHover d-flex">
            Do you want to create one? 
            <a class="anchorTags pl-2" asp-action="Create"><span>   </span>Create New</a>
            <div/>
        </td>
    </tr>
}
else{
    <table border="1" cellpadding="10">
        <thead>
            <tr bgcolor="#845460" style="color:#EAD3CB;">
                <th>
                    @Html.DisplayNameFor(model => model.CreatedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateUpdated)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MeetingDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MeetingParticipants)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ExternalParticipants)
                </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateUpdated)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MeetingDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                @foreach(var participant in item.MeetingParticipants)
                {
                    if (participant.IsChecked)
                    {
                        <div>@participant.FullName</div>
                    }
                }</td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExternalParticipants)
                </td>
                <td class="linkHoverGrey">
                    <a class="anchorTagsPurple" asp-controller="Meetings" asp-action="Selection" asp-route-meetingid="@item.MeetingID">Start</a> |
                    <a class="anchorTagsPurple" asp-action="Edit" asp-route-id="@item.MeetingID">Edit</a> |
                    <a class="anchorTagsPurple" asp-action="Details" asp-route-id="@item.MeetingID">Details</a> |
                    <a class="anchorTagsPurple" asp-action="Delete" asp-route-id="@item.MeetingID">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>
}

MeetingMinutes/Views/Meetings/_ShowMeeting.cshtml
@model Meeting